package ru.itoltec.swypetris

import androidx.compose.foundation.Canvas
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.lerp
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import kotlin.math.round

/** A 16 × 16 pixel sprite with an outline, three body tones, a highlight, and green foliage. */
private data class FruitSprite(val rows: List<String>, val shadow: Color, val body: Color, val light: Color)

/** Parses a compact square-pixel map; dots leave transparent background. */
private fun sprite(shadow: Long, body: Long, light: Long, pixels: String) =
    FruitSprite(pixels.trimIndent().lines(), Color(shadow), Color(body), Color(light))

/** Custom award sprites use upper-left lighting and a darker lower edge for depth. */
private val fruitSprites = mapOf(
    Fruit.CHERRY to sprite(0xFF931E50, 0xFFE53D66, 0xFFFF7890, """
        ................
        .........tt.....
        .......GGtg.....
        ......GGgt......
        ......g.t.t.....
        .....g..t..t....
        ....t...t..t....
        ..oooo..t..t....
        .olllmo...oooo..
        olhhmmso.olllmo.
        olhmmmsoolhhmmso
        ommmmssoolhmmmso
        .omssso.ommmmsso
        ..ooo....omssso.
        ..........oooo..
        ................
    """),
    Fruit.BANANA to sprite(0xFFC0822F, 0xFFF3C840, 0xFFFFE982, """
        ................
        ...........tt...
        ...........to...
        ..........olmo..
        ..........olmo..
        .........olhmo..
        .........olhmo..
        ........olhmso..
        .......olhhmso..
        ..o...olhhmso...
        .omooolhhmmso...
        .olllllhmmso....
        ..ollllmmso.....
        ...ommmsso......
        ....oooooo......
        ................
    """),
    Fruit.GRAPES to sprite(0xFF53328D, 0xFF9460D0, 0xFFC199F4, """
        .......tt.......
        .....GGtgg......
        ....GGGgg.......
        ...ooo.ooo......
        ..olhmolhmo.....
        ..ommsommso.....
        ...ooo.ooo......
        ..olhmolhmo.....
        ..ommsommso.....
        ...oooooo.......
        ....olhmo.......
        ....ommso.......
        .....ooo........
        .....olmo.......
        ......oo........
        ................
    """),
    Fruit.STRAWBERRY to sprite(0xFFA52652, 0xFFEF4C68, 0xFFFF8B91, """
        .......g........
        ....G..g..G.....
        ....GGggGG......
        ...oogGggoo.....
        ..olllggmmso....
        .olhhllllmmso...
        .olhxlmxlmxso...
        .olllllmmmmso...
        ..olxlmxlmso....
        ..ollllmmmso....
        ...omxlmxso.....
        ....ommmso......
        .....omso.......
        ......oo........
        ................
        ................
    """),
    Fruit.APPLE to sprite(0xFF94224C, 0xFFE8415B, 0xFFFF7E82, """
        ........tt......
        ........t.GGG...
        .......tGGgg....
        ...oooo.oo......
        ..olllmommo.....
        .olhhllmmmso....
        .olhhllmmmso....
        olhlllmmmmmso...
        olllllmmmmmso...
        omlllmmmmmsso...
        ommmmmmmmssso...
        .ommmmmmssso....
        .ommmmssssso....
        ..osssoosso.....
        ...ooo.ooo......
        ................
    """),
    Fruit.PEAR to sprite(0xFF4B8643, 0xFFA9C94E, 0xFFDFEC84, """
        ........tt......
        .......t.GG.....
        ......oolgg.....
        .....olhmo......
        .....ollmso.....
        .....ollmso.....
        ....olllmmso....
        ...olhlllmmso...
        ..olhhlllmmso...
        ..olhhllmmmso...
        .olllllmmmmsso..
        .ollllmmmmmsso..
        ..ommmmmmssso...
        ...ommmsssso....
        ....oooooo......
        ................
    """),
    Fruit.PINEAPPLE to sprite(0xFFB57832, 0xFFE9B34B, 0xFFFFDE80, """
        ....G..G........
        ....GG.Gg.G.....
        .....GGGgGg.....
        ...GGgGgGg......
        ....ggGgg.......
        ....oooooo......
        ...ollllmso.....
        ..olhslmsmso....
        ..olslmsmsso....
        ..ollmsmsmso....
        ..olmsmsmsso....
        ..omsmsmssso....
        ..omsmssssso....
        ...omssssso.....
        ....oooooo......
        ................
    """),
    Fruit.WATERMELON to sprite(0xFFB12E56, 0xFFEE5874, 0xFFFF9291, """
        ................
        ................
        ................
        .oooooooooooooo.
        oGllllllllllllGo
        oGllhllmmlmlmlGo
        .oGlxlmxlmxlmGo.
        .oGllmmmmmmmsGo.
        ..oGlmxmmxmlGo..
        ..oGGmmmmmsGGo..
        ...oGGsmsmGGo...
        ....oGGGGGGo....
        .....oggggo.....
        ......oooo......
        ................
        ................
    """)
)

/** Draws crisp square fruit pixels consistently in HUD, help, and results. */
@Composable
fun FruitIcon(fruit: Fruit, modifier: Modifier = Modifier) {
    val sprite = fruitSprites.getValue(fruit)
    val palette = LocalGamePalette.current
    Canvas(modifier.semantics { contentDescription = fruit.title }) {
        val cell = minOf(size.width, size.height) / 16f
        val origin = Offset((size.width - cell * 16) / 2, (size.height - cell * 16) / 2)
        sprite.rows.forEachIndexed { y, row ->
            row.forEachIndexed { x, pixel ->
                val color = when (pixel) {
                    'o' -> palette.fruitOutline
                    's' -> lerp(sprite.shadow, palette.secondary, .10f)
                    'm' -> sprite.body
                    'l' -> lerp(sprite.light, palette.accent, .08f)
                    'h' -> Color(0xFFFFF4CF)
                    'g' -> lerp(Color(0xFF31845C), palette.fruitLeaf, .3f)
                    'G' -> lerp(Color(0xFF8BE07C), palette.fruitLeaf, .3f)
                    't' -> Color(0xFF98603E)
                    'x' -> if (fruit == Fruit.WATERMELON) Color(0xFF582A42) else Color(0xFFFFE39C)
                    else -> Color.Transparent
                }
                if (color != Color.Transparent) {
                    val left = round(origin.x + x * cell)
                    val top = round(origin.y + y * cell)
                    drawRect(color, Offset(left, top), Size(round(origin.x + (x + 1) * cell) - left,
                        round(origin.y + (y + 1) * cell) - top))
                }
            }
        }
    }
}
